name: Daily Empty Commit

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at UTC midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"

      - name: Make empty commit and push
        run: |
          git commit --allow-empty -m "Daily empty commit to keep activity active"
          git push
